### ISSUE TITLE
Issue teszt, és lehetőségek!

### ISSUE THREAD

**Issue by Barni54** [lezsakdomi/labirynth2#8]
- Van **markdown**_!_
- És lista

**Comment by Barni54** [comment]
Szerintem nem éri meg átköltözni WL ről.
Tudom szerkeszteni a kommenteidet! XD

**Comment by lezsakdomi** [comment]
Tesztből lezárom...

**Comment by lezsakdomi** [comment]
De az ebbe tartozik...

**Comment by lezsakdomi** [comment]
Meg mindenki ide fog beírni, aki problémát lát a programban
Főleg ez a fontos
